name: pull_down_button
description: Cupertino styled Pull-Down Button from iOS 14 with great customisation options.
version: 0.5.0
homepage: https://github.com/notDmDrl/pull_down_button
repository: https://github.com/notDmDrl/pull_down_button
issue_tracker: https://github.com/notDmDrl/pull_down_button/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0
  cupertino_range_slider_improved: ^2.0.1
  numberpicker: ^2.1.1

dev_dependencies:
  very_good_analysis: ^3.1.0
